# docker compose -f compose.dev.yaml up --build

services:
  mazanoke:
    build:
      context: .
    environment:
      - USERNAME=test
      - PASSWORD=test
      - METATAGS=true # development
    ports:
      - "3475:80"
    restart: unless-stopped
