name: "Deploy to Github Pages"
on:
  release:
    types:
      - published
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: archive files
        run: |
          tar cf artifact.tar index.html assets/ favicon.ico manifest.json service-worker.js

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            artifact.tar

      - name: deploy to GitHub pages
        uses: actions/deploy-pages@v4
